version: '3'
services:
   app:
     build:
       context: .
       dockerfile: ./docker/php/Dockerfile
     image: php:7.4-fpm
     container_name: application
     restart: unless-stopped
     working_dir: /var/www
     volumes:
       - ./:/var/www
       - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
   nginx:
     image: nginx:alpine
     container_name: webserver
     restart: unless-stopped
     ports:
       - 7777:80
       - 7778:443
     volumes:
       - ./:/var/www
       - ./docker/nginx/conf.d/:/etc/nginx/conf.d


