version: '3'
services:
   app:
     build:
       context: .
       dockerfile: ./docker/php/Dockerfile
     image: php:7.4-fpm-alpine
     #container-name: application
     restart: unless-stopped
     working_dir: /var/www
     volumes:
       - ./:/var/www
       - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
